/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

/**
 * Lean version of CounterDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `CounterDocument.toObject()`. To avoid conflicts with model names, use the type alias `CounterObject`.
 * ```
 * const counterObject = counter.toObject();
 * ```
 */
export type Counter = {
  counterType: string;
  sequence_nr: number;
  _id: string;
};

/**
 * Lean version of OrderDocument
 *
 * This has all Mongoose getters & functions removed. This type will be returned from `OrderDocument.toObject()`. To avoid conflicts with model names, use the type alias `OrderObject`.
 * ```
 * const orderObject = order.toObject();
 * ```
 */
export type Order = {
  _id: string;
};
